// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwbDYxhSCTUYpl_25ks7KyRrj8KOOQXVE',
    appId: '1:487238656975:web:44d7088e8159068fb068ba',
    messagingSenderId: '487238656975',
    projectId: 'memshelf-app',
    authDomain: 'memshelf-app.firebaseapp.com',
    storageBucket: 'memshelf-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8yjRNbF6_UZjSUH4kN7gWnp6LaJqkWiA',
    appId: '1:487238656975:android:9dd78baa9e172353b068ba',
    messagingSenderId: '487238656975',
    projectId: 'memshelf-app',
    storageBucket: 'memshelf-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjRWpHGN4dP-yrKT1G8vGZFFT6-yO7q_w',
    appId: '1:487238656975:ios:f988464caace9af6b068ba',
    messagingSenderId: '487238656975',
    projectId: 'memshelf-app',
    storageBucket: 'memshelf-app.appspot.com',
    iosClientId: '487238656975-9jdjmb549f4iulva58cv8onln8eqtcbk.apps.googleusercontent.com',
    iosBundleId: 'com.memshelf.memshelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjRWpHGN4dP-yrKT1G8vGZFFT6-yO7q_w',
    appId: '1:487238656975:ios:f988464caace9af6b068ba',
    messagingSenderId: '487238656975',
    projectId: 'memshelf-app',
    storageBucket: 'memshelf-app.appspot.com',
    iosClientId: '487238656975-9jdjmb549f4iulva58cv8onln8eqtcbk.apps.googleusercontent.com',
    iosBundleId: 'com.memshelf.memshelf',
  );
}
